---
- name: Setting inital preparations for DATAIKU
  hosts: all

  tasks:
  - name: Create and maintain group "{{dataiku_os_group}}"
    group:
      name: "{{dataiku_os_group}}"
      gid: 10001
      state: present

  - name: Create and maintain user "{{dataiku_os_user}}"
    user:
      name: "{{dataiku_os_user}}"
      comment: Dataiku automation User	  
      uid: 10001
      group: "{{dataiku_os_group}}"

